// Generated by Wrangler by running `wrangler types`

interface Env {
  CloudflareAuthKV: KVNamespace
  FlaudeStorage: KVNamespace
  SESSIONS: DurableObjectNamespace<import('./src/index').MyDurableObject>
  GCHAT_ROOM: Service<import('../xab-gchat-demo/src/broadcaster').RoomProxy>
  AI: Ai
}
